version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    volumes:
      - ./data/db2:/var/lib/postgresql/data2
    env_file:
      - ../.env
    ports:
      - '5432:5432'

  api:
    build :
      context: ../
      dockerfile: Dockerfile.local
    ports : 
      - "8000:8000"
    env_file:
      - ../.env
    volumes: 
      - ../api/:/src
    depends_on:
      - db
    links:
      - db:db


volumes:
  sb:

