# Generated by Django 5.0.3 on 2024-04-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='google_profile',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserGoogleProfle',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
